{
 "title": "FastAPI Observability",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app_name",
    "label": "Application Name",
    "query": {
     "query": "label_values(fastapi_app_info{}, app_name)"
    }
   },
   { "name": "log_keyword", "label": "Log Query" }
  ]
 },
 "panels": [
  {
   "title": "Rate of Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "{{path}}" }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (handler) (rate(http_request_duration_seconds_sum{handler=\"/api/process\"}[1m])) / \r\nsum by (handler) (rate(http_request_duration_seconds_count{handler=\"/api/process\"}[1m]))"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum by (pod) (rate(http_request_duration_seconds_sum{handler=\"/api/process\"}[1m])) / \r\n  sum by (pod) (rate(http_request_duration_seconds_count{handler=\"/api/process\"}[1m]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=\"404\"}[60m]))"
    },
    {
     "expr": "rate(http_requests_total{status=\"4xx\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{job=\"deid-medcat-service\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Request In Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 13, "y": 17 },
   "targets": [
    {
     "expr": "http_requests_total{path!=\"/metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=\"2xx\"}[60m])) / sum(rate(http_requests_total[60m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percent of 4xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=\"4xx\"}[60m])) / sum(rate(http_requests_total[60m]))",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "http_requests_total{status=\"4xx\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PR 99 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[60m])) by (le))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Request Duration over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  rate(http_request_duration_seconds_sum{handler=\"/api/process\"}[1m])\r\n) / \r\nsum by (pod) (\r\n  rate(http_request_duration_seconds_count{handler=\"/api/process\"}[1m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}