apiVersion: v2
name: cogstack-jupyterhub-helm
description: A Helm chart for CogStack Jupyter Hub using official JupyterHub chart
type: application
version: 0.0.1
appVersion: "latest"

maintainers:
  - name: alhendrickson
    email: alistair@cogstack.org
  - name: jocelyneholdbrook
    email: jocelyne@cogstack.org

icon: "https://avatars.githubusercontent.com/u/28688163"

dependencies:
  - name: jupyterhub
    version: 4.3.2
    repository: https://hub.jupyter.org/helm-chart/
