{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "cogstack-cohort.fullname" . }}
  labels:
    {{- include "cogstack-cohort.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "cogstack-cohort.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    {{- if .Values.networkPolicy.egress.enabled }}
    - Egress
    {{- end }}
  ingress:
    # Allow traffic to webapp from anywhere
    - to:
      - podSelector:
          matchLabels:
            {{- include "cogstack-cohort.webapp.selectorLabels" . | nindent 12 }}
      ports:
        - protocol: TCP
          port: {{ .Values.webapp.service.port }}
    # Allow traffic to medcat from nl2dsl and webapp
    - to:
      - podSelector:
          matchLabels:
            {{- include "cogstack-cohort.medcat.selectorLabels" . | nindent 12 }}
      from:
      - podSelector:
          matchLabels:
            {{- include "cogstack-cohort.nl2dsl.selectorLabels" . | nindent 12 }}
      - podSelector:
          matchLabels:
            {{- include "cogstack-cohort.webapp.selectorLabels" . | nindent 12 }}
      ports:
        - protocol: TCP
          port: {{ .Values.medcat.service.port }}
    # Allow traffic to ollama from nl2dsl
    - to:
      - podSelector:
          matchLabels:
            {{- include "cogstack-cohort.ollama.selectorLabels" . | nindent 12 }}
      from:
      - podSelector:
          matchLabels:
            {{- include "cogstack-cohort.nl2dsl.selectorLabels" . | nindent 12 }}
      ports:
        - protocol: TCP
          port: {{ .Values.ollama.service.port }}
    # Allow traffic to nl2dsl from webapp
    - to:
      - podSelector:
          matchLabels:
            {{- include "cogstack-cohort.nl2dsl.selectorLabels" . | nindent 12 }}
      from:
      - podSelector:
          matchLabels:
            {{- include "cogstack-cohort.webapp.selectorLabels" . | nindent 12 }}
      ports:
        - protocol: TCP
          port: {{ .Values.nl2dsl.service.port }}
  {{- if .Values.networkPolicy.egress.enabled }}
  egress:
    {{- with .Values.networkPolicy.egress.egressRules }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
